<a href="https://colab.research.google.com/github/Kuldeep995/Machine_Learning/blob/master/Assignment0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is Zeroth Assignment

Sol 1.

In [ ]:
import sys
print("python version used is:")
print(sys.version)

python version used is:
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]


Sol 2.


In [ ]:
import site
print("located python site packages:")
print(site.getsitepackages())

located python site packages:
['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']


Sol 3.

In [ ]:
import inspect, os
print(inspect.getfile(inspect.currentframe()))
print(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))

<ipython-input-2-999536cf70d4>
/content


Sol 4.

In [ ]:
 import numpy as np
 A = np.round(np.random.rand(2,3)*10)
 b = np.round(np.random.rand(3,2)*10)
 C = A.dot(b)
 print(A)
 print(b)
print(C)

[[9. 2. 7.]
 [7. 8. 1.]]
[[6. 6.]
 [2. 6.]
 [5. 4.]]
[[93. 94.]
 [63. 94.]]


Sol 5.

In [ ]:
import numpy as np
C=0
for x in range(2, 6):
   A = np.round(np.random.rand(2,3)*10)
   b = np.round(np.random.rand(3,2)*10)
   C = C+A.dot(b)
   print(A)
   print(b)
print(C/5)

[[6. 0. 1.]
 [4. 2. 6.]]
[[10.  7.]
 [ 3.  6.]
 [ 4.  2.]]
[[ 9.  2. 10.]
 [ 8.  1.  8.]]
[[1. 8.]
 [9. 7.]
 [5. 2.]]
[[6. 4. 8.]
 [1. 2. 4.]]
[[ 9.  4.]
 [ 2.  5.]
 [10.  7.]]
[[7. 3. 6.]
 [6. 2. 3.]]
[[4. 5.]
 [6. 0.]
 [5. 0.]]
[[71.8 57. ]
 [46.2 42.2]]


Sol 6.

In [ ]:

print(C) 
np.savetxt('test.csv',C/5,delimiter=',')
C=np.genfromtxt('test.csv',delimiter=',')
print(C.transpose())

[[22.976 18.24 ]
 [14.784 13.504]]
[[4.5952 2.9568]
 [3.648  2.7008]]


Sol 7.

In [ ]:
print(C)
x = np.mean(C)
print("mean is: ",x)
x = np.median(C)
print("median is: ",x)
from scipy import stats
x = stats.mode(C)
print("mode is: ",x)

[[4.5952 3.648 ]
 [2.9568 2.7008]]
mean is:  3.475200000000001
median is:  3.3024000000000004
mode is:  ModeResult(mode=array([[2.9568, 2.7008]]), count=array([[1, 1]]))


Sol 8.

In [ ]:
result  = C[np.triu_indices(2)]
print("Extracted upper triangular part of the array C:")
print(result)

Extracted upper triangular part of the array C:
[4.5952 3.648  2.7008]


Sol 9.

In [ ]:
n=input("enter column num")

nn=int(n)

import csv
with open('test.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
          print(row[nn])

enter column num1
3.648000000000000576e+00
2.700800000000000090e+00


Sol 10.

In [ ]:
n=input("enter the num to be replaced")
nn=int(n)
import csv
with open('test.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        if(row)
        #not completed 
