<a href="https://colab.research.google.com/github/Kuldeep995/Machine_Learning/blob/master/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part 1**

Sol 1.

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:", array)
array=np.ones(10)
print("An array of 10 ones:", array)
array=np.ones(10)*5
print("An array of 10 fives:", array)


An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


sol 2.

In [ ]:
array=np.arange(10,52,2)
print("Array of all the even integers from 10 to 50")
print(array)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Sol 3.

In [ ]:
from numpy import random

x = random.rand(3, 3)

print(x)

[[0.24854591 0.7586037  0.38503101]
 [0.63346115 0.78146671 0.5892011 ]
 [0.17768007 0.98404679 0.41497293]]


Sol 4.

In [ ]:

import numpy as np
x = random.rand(3, 3)

print(x)
np.savetxt('file1.txt', x , fmt= '%f')
arr = np.genfromtxt("file1.txt")
arr

[[0.47857768 0.17791496 0.73705301]
 [0.86923292 0.85594241 0.21150065]
 [0.54531503 0.55674009 0.47702185]]


array([[0.478578, 0.177915, 0.737053],
       [0.869233, 0.855942, 0.211501],
       [0.545315, 0.55674 , 0.477022]])

**`Part 2`**

Sol 1.

In [ ]:
from PIL import Image
import numpy as np
import pandas as pd
import csv
from google.colab import files
from io import BytesIO


uploaded = files.upload()
img = Image.open(BytesIO(uploaded['python.png'])).convert('L')

arr_i = np.array(img)
print(arr_i)
data = pd.DataFrame(arr_i)
print(data)

f_csv = data.to_csv('python_pic_df.csv')
print("This got stored in the CSV file.")

Saving python.png to python (5).png
[[105 106 103 ... 105 104 105]
 [109 109 104 ... 107 112 113]
 [111 110 105 ... 109 121 121]
 ...
 [ 51  47  44 ... 117 111 111]
 [ 47  45  43 ... 112 110 110]
 [ 42  42  42 ... 105 108 108]]
      0     1     2     3     4     5     ...  1108  1109  1110  1111  1112  1113
0      105   106   103    99   102   106  ...   100   100   103   105   104   105
1      109   109   104    98    97   101  ...   101   102   104   107   112   113
2      111   110   105    98    94    95  ...   103   104   106   109   121   121
3      106   107   105   100    96    94  ...   105   105   107   109   123   123
4       98   100   103   104   101    97  ...   105   105   106   108   116   116
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
1275    40    40    42    47    52    56  ...   117   117   118   119   117   117
1276    47    45    43    44    47    50  ...   117   117   117   118   112   112
1277    51    47    44    42    44

Sol 2.

In [ ]:
df = data.iloc[:(len(data)-1)]

df = df[df.columns[:-1]]
print(df)
ex_file = df.to_excel('pythonpic_excel.xlsx')
print("This got stored in the Excel file..")

      0     1     2     3     4     5     ...  1107  1108  1109  1110  1111  1112
0      105   106   103    99   102   106  ...   102   100   100   103   105   104
1      109   109   104    98    97   101  ...   103   101   102   104   107   112
2      111   110   105    98    94    95  ...   105   103   104   106   109   121
3      106   107   105   100    96    94  ...   106   105   105   107   109   123
4       98   100   103   104   101    97  ...   107   105   105   106   108   116
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
1274    39    40    44    50    56    60  ...   119   119   119   120   121   121
1275    40    40    42    47    52    56  ...   118   117   117   118   119   117
1276    47    45    43    44    47    50  ...   119   117   117   117   118   112
1277    51    47    44    42    44    46  ...   122   119   117   117   117   111
1278    47    45    43    42    44    45  ...   120   116   113   112   112   110

[1279 rows x 11

 Sol 3.

In [ ]:
import datetime as dt
date = dt.date.today()
print("Today is:",date)

Today is: 2020-08-23


**Part** **3**

Sol 1.

In [ ]:
print("Enter DOB in format YYYY-MM-DD:")
dob  = str(input())

dob_dt = dt.datetime.strptime(dob, '%Y-%m-%d').date()

age = today.year - dob_dt.year
if today.month < dob_dt.month:
  age = age - 1
elif today.month == dob_dt.month and today.day < dob_dt.day:
  age = age - 1
print('Your age is:',age,'years')


Enter DOB in format YYYY-MM-DD:
1999-04-09
Your age: 21 years
